alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: app-1db9dc78-0eb5-4537-8b4a-b355cb7e246c
  db_name: db
  db_user: db
  engine: PG
  name: db
  num_nodes: 1
  production: true
  size: db-s-dev-database
  version: "12"
functions:
- envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: jonfriesen/fn-todo
  name: fn-todo
  routes:
  - path: /fn-todo
  source_dir: /
name: sample-html
region: tor
static_sites:
- environment_slug: html
  git:
    branch: main
    repo_clone_url: https://github.com/digitalocean/sample-html.git
  name: sample-html
  routes:
  - path: /
  source_dir: /